### ISSUE TITLE
Feature request: add an interval setting. 

### ISSUE THREAD

**Issue by matrover** [biemond/com.athom.awair#2]
add an setting in de app configuration for the interval of quering the api

**Comment by biemond** [comment]
Hi,

current it is ```Homey.ManagerCron.registerTask(cronName, "*/5 * * * *", settings)``` which is the minimal else you get a 24 hour ban.

So you want to have to do this less or more often

thanks

**Comment by matrover** [comment]
Thanks, and the */5 is in minutes or seconds?

**Comment by biemond** [comment]
it is every 5 minute on the clock
