### ISSUE TITLE
No values

### ISSUE THREAD

**Issue by rgerr** [biemond/com.athom.awair#4]
Hi there,

Thanks for the Homey plug-in. However, I am not receiving any data to my Homey from my Awair Mint.

**Comment by biemond** [comment]
Thanks, 
Ok I dont know this mint device ( it looks like a business one), can you share or create an api key so I can fix this for you. After that you can change or delete the key again

please send it to biemond at gmail dot com

**Comment by biemond** [comment]
thanks it works now for me, it looks like mint does not have the co2 sensor and has lux as new sensor. 
I published 0.0.6 for review. probably it some  days.

**Comment by rgerr** [comment]
Thanks allot, will let you know if it works!

**Comment by biemond** [comment]
the new version 0.0.6 is published, it can be you have to reset or remove your current awair device because I added the lux sensor to the list, which was not there in version 0.0.5

**Comment by rgerr** [comment]
Great, seems to be working just fine! Thanks allot!
