### ISSUE TITLE
The pm2.5 isn't update after setup

### ISSUE THREAD

**Issue by pjmpessers** [biemond/com.athom.awair#8]
Just recieved the awair element and connected to the awair app. It receives the data just fine on there app. Got a api-key and connected without a problem to homey. Every 5 minutes it receives the new values exept pm2.5. It receives a value after setup, but then it stops. I tried everything that was possible.

Also would it be possible to change the value of refreshing the values sooner. 

Thanks.

Update: it seems that it is updating. Unless the value of the pm2.5 is to high. A reading of 200 or more isn't recieved

**Comment by biemond** [comment]
oh wow, element is new.  let me check mine. maybe they changed something on the response.

faster refresh is not possible for us, you will be blocked for 24 hours.

**Comment by biemond** [comment]
thanks let me check the high value.

**Comment by biemond** [comment]
max 80 for me. let me check this
```		"measure_pm25": {
			"type": "number",
			"title": {
				"en": "Current PM2.5 value"
			},
			"getable": true,
			"setable": false,
			"units": {
				"en": "ug/m"
			},
			"min": 0,
			"max": 80,
			"decimals": 0,
			"insights": true,
			"uiComponent": "sensor"
		},```

**Comment by biemond** [comment]
can you open the awair app and click on pm2.5 ,for me it is from 0 to 80.

**Comment by pjmpessers** [comment]
Thank you for the quick response, Edwin. 

Awair element should be the same as the awair 2nd edition. Only a plastic housing. 

Thank you for explaining that the time limitation lays at the server of awair and that the don't let us contact the server shorter than once every 5 minutes.

I have someone in the household that smokes and on the awair app it came over 600. That value won't be pushed to homey.

My intention is to speed up my mechanical ventilation once that it notice my pm2.5 goes up by cooking in the kitchen.

**Comment by biemond** [comment]
cool , I will change it to 800

**Comment by pjmpessers** [comment]
![Screenshot_20200724-174835_Awair Home](https://user-images.githubusercontent.com/34476404/88410838-36d7da80-cdd7-11ea-8aa0-ba70941d6294.jpg)

**Comment by pjmpessers** [comment]
That was quick. Thanks.

**Comment by pjmpessers** [comment]
Is it possible to place the update on github. So i could check it?

**Comment by biemond** [comment]
https://github.com/biemond/com.athom.awair/blob/master/app.json#L236 change this

**Comment by pjmpessers** [comment]
Thanks.

It worked. Top. 😉

![Screenshot_20200724-213853_Homey](https://user-images.githubusercontent.com/34476404/88429066-4c103180-cdf6-11ea-8bc9-05fcb59ae980.jpg)

**Comment by pjmpessers** [comment]
[Awair.zip](https://github.com/biemond/com.athom.awair/files/4973952/Awair.zip)

**Comment by biemond** [comment]
perfect, will publish it. or no smokers inside the house

**Comment by pjmpessers** [comment]
Haha.

I try him to quit.  And hoped he would see how unhealthy it is by this awair meter. But it doen't help.

**Comment by pjmpessers** [comment]
Thanks for the help.
